version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  redis:
    image: redis:alpine
    ports:
      - "${port}:6379"
    env_file:
      - .env
      